_target_: tomo.initializers.unet_initializer.SRInitializerNet
input_channels: 1
output_channels: 1
base_filters: 64
use_attention: false
use_residual: true
tof_input_height: ${data.tof_grid_height}
tof_input_width: ${data.tof_grid_width}
output_height: ${data.anatomy_height}
output_width: ${data.anatomy_width}
